### ISSUE TITLE
IPv6 lookup returns unknown

### ISSUE THREAD

**Issue by Rod-Gomes** [varnish/libvmod-geoip#16] opened 2018-07-19 21:04 UTC
Note: I opened another issue, but it was closed. I do not know if I should open a new one or answer the old issue. #15 

I'm trying to get the country code from an IPv6 and returns **unknown** every time.

I have the default GeoIP databases installed (Including the IPv6 database.).
```
[~]# ls /usr/share/GeoIP
./   GeoIP.dat@      GeoIP-initial.dat  GeoIPv6-initial.dat
../  GeoIP.dat.test  GeoIPv6.dat@ 
[~]# yum list installed | grep -i geoip
GeoIP.x86_64                               1.5.0-11.el7                @base    
GeoIP-devel.x86_64                         1.5.0-11.el7                @cloudlinux-x86_64-server-7
GeoIP-update.noarch                        1.5.0-11.el7                @cloudlinux-x86_64-server-7
```

`geoiplookup6` Lookup IPv6 normally:
```
[~]# geoiplookup6 2804:14c:87c1:8a3d::1005
GeoIP Country V6 Edition: BR, Brazil
```

```
[root@test ~]# cat /etc/*-release
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
```

But, `geoip.country_code(client.ip)` does not lookup the same IPv6 above.

Is there any special configuration for lookup the country with IPv6?
Do I need to configure the IPv6 database somewhere?

**Comment by gquintard** [comment] 2018-07-19 21:11
I already answered on the other ticket that you should not open tickets
without first reach out to support channels first.

Turns out, I haven't had the time to look at this, but it seems like it's
more of a feature request than a bug.

-- 
Guillaume Quintard

**Comment by gquintard** [comment] 2018-07-19 21:35
So, I had a look at it, this is a feature request not a bug, so I'm going to close it as we only keep bugs here.

However the code shouldn't be too hard to write, I'll be happy to assist you write it and/or review the PR.

**Closed as completed by gquintard** 2018-07-19 21:35 UTC
Labels: a=backport-review-4.0

**Comment by Rod-Gomes** [comment] 2018-07-19 21:41
Hello @gquintard,

Thanks for looking at this. I did not know that the module did not support IPv6, I instinctively thought so.

> However the code shouldn't be too hard to write, I'll be happy to assist you write it and/or review the PR.

Thank you!
